# workflowの名前
name: Rsync server actions

# トリガーの設定
on:
  push:
    branches: main # mainブランチの場合はmainに変更

jobs:
  build:
    runs-on: ubuntu-latest # 実行環境の設定

    steps:
      - uses: actions/checkout@v2

      - name: rsync deployments
        uses: burnett01/rsync-deployments@5.2
        with:
          switches: -avzr --delete
          path: .
          remote_path: /home/nyc/nycreation.jp/lftp/
          remote_host: 160.251.44.55
          remote_user: nyc
          remote_key: ${{ secrets.PRIVATE_KEY }}
          remote_port: ${{ secrets.DEPLOY_PORT }}
